apiVersion: v1
kind: Service
metadata:
  name: {{include "wildduck.webmail.fullname" .}}
  labels: {{- include "wildduck.webmail.labels" . | nindent 4}}
spec:
  type: {{.Values.webmail.service.type}}
  ports:
    - port: {{.Values.webmail.service.port}}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "wildduck.webmail.selectorLabels" . | nindent 4}}
